# Generated by Django 5.1.2 on 2025-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_checkoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='mmyy',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
