# Generated by Django 5.1.2 on 2025-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_checkoutmodel_card_number_checkoutmodel_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='cvv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
