# Generated by Django 5.1.2 on 2025-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_checkoutmodel_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='card_number',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
    ]
