# Generated by Django 5.1.2 on 2025-01-17 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_checkoutmodel_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='mmyy',
            field=models.CharField(max_length=5),
        ),
    ]
